# Generated by Django 3.2.3 on 2021-07-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'basket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('effect', models.CharField(max_length=30)),
                ('ingredient', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('grade', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('skin_type', models.TextField()),
                ('pro_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cosmetics',
                'managed': False,
            },
        ),
    ]
